appun:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

ecommerce:
    resource: "@EcommerceBundle/Resources/config/routing.yml"
    prefix:   /eco

changt_langue:
    path:     /{id}/changtlangue
    defaults: { _controller: AppBundle:Homepage:changtLangue }
    methods:  GET

